version: '3'
# dotenv:
#   - '.env'

vars:
  BINARY: '{{.BINARY| default "tui"}}'

tasks:
  lint:
    summary: Run lint with clippy
    cmds:
      - cargo clippy
  test:
    summary: Run unit test with logs
    cmds:
      - RUST_LOG=debug cargo test -- --nocapture --test-threads=1
  fmt:
    summary: Run rust formatting with fmt
    cmds:
      - cargo fmt
  audit:
    summary: Run rust audit with cargo-deny
    cmds:
      - cargo deny check advisories
  run:
    summary: Run application with hot-reload
    cmds:
      - cargo watch -s 'cargo run --package {{.BINARY}} -- -release'
  run-wasm:
    summary: Run wasm application
    cmds:
      - cd gui && RUSTFLAGS='--cfg getrandom_backend="wasm_js"' trunk serve --release --dist ../web/dist/
  build-wasm:
    summary: Build wasm distribution
    cmds:
      - cd gui && RUSTFLAGS='--cfg getrandom_backend="wasm_js"' trunk serve --release --dist ../web/dist/ --minify
  update-version:
    summary: Update version manifest
    cmds:
      - |
        cat <<EOF> version.json
        {
          "version": "$(cat internal/Cargo.toml| grep '^version' | awk -F '=' '{print $2}' | sed 's/[[:space:]|\"]//g')",
          "build_date": "$(date +%F)",
          "build_hash": "$(git rev-parse HEAD)"
        }
        EOF
